import Head from "next/head";
import Link from "next/link";
import Prismic from "prismic-javascript";

import Header from "../components/Header/Header";
import Links from "../components/Links/Links";

import { client } from "../prismic-configuration";

export default function Home({ posts }) {
	console.log(posts);
	return (
		<div className="container">
			<Head>
				<title>Christian Peterson</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header></Header>
			<Links></Links>
			<h2>bio</h2>
			<p>
				I'm a student at the University of Arizona, majoring in Computer
				Science with a minor in Music. In my freetime, I make music,
				read, play video games, and bike. Join me on my journey!
			</p>
			<h2>blog</h2>
			<ul>
				{posts &&
					posts.map((post, i) => (
						<li key={i}>
							<Link href={`/posts/${post.uid}`}>
								{post.data.title[0].text}
							</Link>
						</li>
					))}
			</ul>
		</div>
	);
}

export async function getStaticProps() {
	const posts = await client.query(
		Prismic.Predicates.at("document.type", "post"),
		{ orderings: "[my.post.date desc]" }
	);
	return {
		props: {
			posts: posts.results,
		},
	};
}
